# Training configs for Seg

dataset : rice Dataset
n_classes : 3
channels : 6
ignore_index : 255
net : Attention_UNet
optimizer : adam
scheduler : StepLR
lr : 0.0001
batchsize : 8
start_epoch : 0
end_epoch : 100
result_dir : "D:/BARELAND/NET/attnUnet-adam-0.01_six"
criterion : weight_crossentropy
logIterval : 10
valIterval : 2
resume :
  flag : False
#  state_path : "./eventfiles-UNet-channels7/UNet-ep.pth"·